# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 448720cec781d928d0056631735071005c0501c8d24e2f556d37ee3cfb47b004f5f9e876e53ed3e6aac2556dfe664a324f616550f886aa6695c7e9b447e674a9

test:
  secret_key_base: 425ea35aea1364f3c1c9b84441edda2129d8db7307b182f9d8edf376ff2eca926f35864ede380c6308157bee26b7351667d206bb9e6ce99ffb62c9dbf4107313

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
